# Generated by Django 3.1 on 2020-08-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dropbox',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('path', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('shared_with', models.CharField(default='', max_length=100)),
                ('matching_terms', models.CharField(default='', max_length=100)),
                ('created', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='slack',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('channel', models.CharField(default='', max_length=100)),
                ('author', models.CharField(default='', max_length=100)),
                ('message', models.CharField(default='', max_length=100)),
                ('matching_terms', models.CharField(default='', max_length=100)),
                ('time_stamp', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tweet',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('user', models.CharField(default='', max_length=100)),
                ('message', models.CharField(default='', max_length=100)),
                ('time_stamp', models.CharField(default='', max_length=100)),
                ('matching_terms', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
