# Generated by Django 3.1 on 2020-08-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme_search', '0002_dropbox_slack_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dropbox',
            name='id',
            field=models.IntegerField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slack',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
